baseURL = 'https://lulu0217.github.io/'
languageCode = 'en-us'
title = 'Lu Zhang'
theme = 'PaperMod'
[pagination]
  pagerSize = 5

[params]
  author = 'Lu Zhang'
  description = 'Personal website of Lu Zhang â€” Researcher'
  env = 'production'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

  [params.homeInfoParams]
    Title = "Hi, I'm Lu Zhang"
    Content = """Postdoctoral Researcher at [IRDL, UMR CNRS 6027](https://www.irdl.fr/), University of Brest, France.\n\n\
My research focuses on AI & Deep Learning for time-series forecasting, fault diagnosis, digital twins, and prognostics of electrical systems and batteries."""

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/LuLu0217'

  [[params.socialIcons]]
    name = 'email'
    url = 'mailto:luzhang0216@gmail.com'

  [[params.socialIcons]]
    name = 'googlescholar'
    url = 'https://scholar.google.com/citations?user=YOUR_ID'

[params.cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = false

[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 10

[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 20

[[menu.main]]
  identifier = 'publications'
  name = 'Publications'
  url = '/publications/'
  weight = 30

[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 40

[[menu.main]]
  identifier = 'search'
  name = 'Search'
  url = '/search/'
  weight = 50

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = false
